FROM restic/restic:0.16.0

ARG UID=1000
ENV UID=$UID

ARG GID=1000
ENV GID=$GID

ARG RESTIC_PASSWORD
ENV RESTIC_PASSWORD=$RESTIC_PASSWORD

ARG RESTIC_ROOT="/srv/restic"
ENV RESTIC_ROOT=$RESTIC_ROOT

ARG RESTIC_REMOTE="remote:restic"
ENV RESTIC_REMOTE=$RESTIC_REMOTE

ARG RESTIC_BACKUP_KEEP_DAILY="7"
ENV RESTIC_BACKUP_KEEP_DAILY=$RESTIC_BACKUP_KEEP_DAILY

ARG RESTIC_BACKUP_KEEP_WEEKLY="4"
ENV RESTIC_BACKUP_KEEP_WEEKLY=$RESTIC_BACKUP_KEEP_WEEKLY

ARG RESTIC_BACKUP_KEEP_MONTHLY="12"
ENV RESTIC_BACKUP_KEEP_MONTHLY=$RESTIC_BACKUP_KEEP_MONTHLY

ARG RESTIC_BACKUP_KEEP_YEARLY="2"
ENV RESTIC_BACKUP_KEEP_YEARLY=$RESTIC_BACKUP_KEEP_YEARLY

ARG RESTIC_DUMP_KEEP_LAST="8"
ENV RESTIC_DUMP_KEEP_LAST=$RESTIC_DUMP_KEEP_LAST

ARG RESTIC_CMD_LOCK_TIMEOUT="21600"
ENV RESTIC_CMD_LOCK_TIMEOUT=$RESTIC_CMD_LOCK_TIMEOUT

ARG RESTIC_STOP_CONTAINER_LABEL="restic-stop=true"
ENV RESTIC_STOP_CONTAINER_LABEL=$RESTIC_STOP_CONTAINER_LABEL

# add commands to PATH for convenient execution
ENV PATH="$RESTIC_ROOT/cmd:$PATH"

# change rclone config path
ENV RCLONE_CONFIG="/etc/rclone/rclone.conf"

COPY . $RESTIC_ROOT

RUN apk update \
    && apk add \
        docker~=23.0.6 \
        rclone~=1.62.2 \
        flock~=2.38.1 \
        supercronic~=0.2.24 \
    && addgroup -g $GID restic \
    && adduser -D -u $UID -G restic restic \
    && chmod -R 755 \
        $RESTIC_ROOT/cmd \
        $RESTIC_ROOT/scripts \
        $RESTIC_ROOT/entrypoint.sh \
    && mkdir -p \
        $RESTIC_ROOT/source \
        $RESTIC_ROOT/target \
        $RESTIC_ROOT/target/repository \
        $RESTIC_ROOT/target/export \
    && chown -R restic:restic $RESTIC_ROOT

USER restic

ENTRYPOINT ["/bin/sh", "-c", "$RESTIC_ROOT/entrypoint.sh"]
