#!/bin/sh

log -i "Attempting to acquire lock for task CHECK with timeout of ${RESTIC_COMMAND_LOCK_TIMEOUT} seconds ..."

flock \
  -w ${RESTIC_COMMAND_LOCK_TIMEOUT} \
  -x ${RESTIC_COMMAND_LOCK_FILE} \
  -c "/usr/local/sbin/restic/check.sh"
