#!/bin/sh

log -i "Attempting to acquire lock for task DUMP with timeout of ${RESTIC_LOCK_TIMEOUT} seconds ..."

flock \
  -w ${RESTIC_LOCK_TIMEOUT} \
  -x ${RESTIC_LOCK_FILE} \
  -c "/usr/local/sbin/restic/dump.sh"
