#!/bin/sh

script_dir=$(dirname "$0")
error=0

if [ "$(id -u)" != "$(id restic -u)" ]; then
  log -e "This script can only be executed by user 'restic'."
  exit 1
fi

(
  log -i "Attempting to acquire lock for task CHECK with timeout of ${RESTIC_LOCK_TIMEOUT} seconds ..."
  flock --timeout ${RESTIC_LOCK_TIMEOUT} --exclusive 200

  log -i "Starting task CHECK ..."
  ${script_dir}/_backup/check.sh || error=1
  ${script_dir}/_dump/check.sh || error=1
  ${script_dir}/_sync/check.sh || error=1

  if [ $? -ne 0 ] || [ ${error} == 1 ]; then
    log -e "Completed task CHECK with errors. Check log output above."
    exit 1
  else
    log -i "Completed task CHECK. Check log output above."
  fi
) 200> "${script_dir}/restic.lock"
