#!/bin/sh

blue="\033[1;34m"
yellow="\033[1;33m"
red="\033[1;31m"
reset="\033[0m"

log() {
  local timestamp="$(date +'%Y-%m-%d %H:%M:%S')"
  echo -e "[${timestamp}] ${1}: ${2}"
}

if [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
  echo "Usage: log [TYPE] [MESSAGE]"
  echo "  -h, --help    Display help"
  echo "  -i, --info    Log info message"
  echo "  -w, --warning Log warn message"
  echo "  -e, --error   Log error message"
  exit 0
fi

if [ -z "${1}" ] || [ -z "${2}" ]; then
  echo "Invalid arguments. Please see usage by using -h or --help."
  exit 1
fi

if [ "${1}" == "-i" ] || [ "${1}" == "--info" ]; then
  log "${blue}INF${reset}" "${2}"
fi

if [ "${1}" == "-w" ] || [ "${1}" == "--warning" ]; then
  log "${yellow}WRN${reset}" "${2}"
fi

if [ "${1}" == "-e" ] || [ "${1}" == "--error" ]; then
  log "${red}ERR${reset}" "${2}"
fi
