#!/bin/sh

script_dir=$(dirname "$0")

if [ "$(id -u)" != "$(id restic -u)" ]; then
  log -e "This script can only be executed by user 'restic'."
  exit 1
fi

(
  log -i "Attempting to acquire lock for task SYNC with timeout of ${RESTIC_LOCK_TIMEOUT} seconds ..."
  flock --timeout ${RESTIC_LOCK_TIMEOUT} --exclusive 200

  log -i "Starting task SYNC ..."
  ${script_dir}/_sync/execute.sh && \
  {
    if [[ "${*}" =~ "--check" ]]; then
      ${script_dir}/_sync/check.sh
    fi
  }

  if [ $? -ne 0 ]; then
    log -e "Completed task SYNC with errors. Check log output above."
    exit 1
  else
    log -i "Completed task SYNC. Check log output above."
  fi
) 200> "${script_dir}/restic.lock"
